# Generated by Django 4.0.3 on 2022-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmp_data',
            name='time',
            field=models.DateTimeField(default=0, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
